### ISSUE TITLE
overriding `current_user` can conflict with common libraries such as Devise

### ISSUE THREAD

**Issue by kevinmtrowbridge** [togglepro/pundit-resources#16]
Hi!

Your gem is lovely, cutting-edge (in my opinion) due to the rising stars of JSONApi::Resources and Pundit, and is working super well for me.

I had two issues while integrating it:
- The master branch works with Rails 4.x but, the released version on Rubygems, does not -- so I had to specifically point bundler at the Github repo.  No biggie but, I honestly believe a good number of folks using this library will be on 4.x for a while yet.  **Suggestion: rev the version on Rubygems.**
- I use Devise, and Devise's `current_user` method -- the way you override `current_user` to raise an exception telling me that I haven't set `current_user` ... I was reading blog posts about how to meta-undefine or remove methods, and then I just gave up and, copied your gem into my lib directory and commented out that method.  **Suggestion: overriding that method is not really necessary and, just documenting is probably enough.**

Thanks for your gem!  I love how it calls into Pundit's scopes ... I was surprised at how tiny and how well it fit bridges the gap between Pundit & JSONApi::Resources.

In particular, I have been fighting to use JSONApi::Resources -- I really prefer that approach and I see that the Rails team has also been encouraging them.  My two big problems with it were: fine-grained integration with Pundit & Devise, and caching.  Your gem solved the first.  Caching, I see in their Github issues that they are working on this.

KT

**Comment by barelyknown** [comment]
@penman Can you up the version, publish to rubygems, and close this issue? Thanks.

**Comment by alyssais** [comment]
Done!
