### ISSUE TITLE
Add tests for relationship controller actions

### ISSUE THREAD

**Issue by alyssais** [togglepro/pundit-resources#4]
Currently, only the following actions are tested:
- `create`
- `destroy`
- `index`
- `show`
- `update`

This means that there are no tests for these actions:
- [x] `get_related_resource`
- [x] `get_related_resources`
- [x] `show_relationship`
- [x] `update_relationship`
- [x] `destroy_relationship`
- [x] `create_relationship`

**Comment by alyssais** [comment]
I'll check these off as I implement them in my local branch.

**Comment by alyssais** [comment]
`create_relationship` is causing me some problems.
It doesn't currently work with pundit-resources because of the way it's implemented in JSONAPI::Resources. There's not really a way to get access to the resource that's going to be updated before it is updated. It doesn't even get its relationship attribute updated _until_ the whole thing is saved.

**Comment by valscion** [comment]
Yeah, I really hated that, too 😞 . We had to do some [nasty hacking around with stubs and all](https://github.com/venuu/jsonapi-authorization/pull/10/commits/cf151d8930ddd7f356be2ff6505a4ae9c4276a91) to test for that special action in `jsonapi-authorization`. If you put up a PR of your changes I might be able to help with the `create_relationship` testing strategy :)

**Comment by alyssais** [comment]
@valscion the problem here isn't that I can't test it (I can accomplish that well enough by testing scenarios, I think), it's that I haven't been able to hook into the code that creates the relationship, so that action currently doesn't authorize at all.

**Comment by alyssais** [comment]
I've opened an issue (cerebris/jsonapi-resources#727) to point out that the save callbacks aren't fired when a model is modified through `create_relationship`. I'll see what they say there, because if that could be changed this would be easy.

**Comment by alyssais** [comment]
@valscion here's the [branch](https://github.com/togglepro/pundit-resources/compare/master...penman:relationship-tests?expand=1) with the tests for the other actions anyway, though

**Comment by valscion** [comment]
> callbacks aren't fired when a model is modified through create_relationship

Oh damn, that's disappointing. Hopefully the issue will be resolved with some backportable manner.

**Comment by valscion** [comment]
> @valscion here's the branch with the tests for the other actions anyway, though

Nice, looking very good :) Much easier to follow these specs than `jsonapi-authorization` request specs 😅 .

**Comment by alyssais** [comment]
cerebris/jsonapi-resources#739 looks like it might address this issue.

**Comment by alyssais** [comment]
Yep, once cerebris/jsonapi-resources#739 is merged we're good on this.

**Comment by alyssais** [comment]
cerebris/jsonapi-resources#739 is now in master, so we just need to wait for them to release a new version and we can get this merged in.
